In [3]:
import math
print('Enter the range (How Many Number You want to Enter):')
Num = int(input())
D = []
for i in range(Num):
    print('Enter The Values:')
    N = int(input())
    D.append(N)
print('Enter Number are:',D)

C = 50
H = 30

for i in range(Num):
    Q = round(math.sqrt((2*C*D[i])/H))
    print('Ouput for',D[i],'is:',Q)

Enter the range (How Many Number You want to Enter):


 3


Enter The Values:


 100


Enter The Values:


 150


Enter The Values:


 180


Enter Number are: [100, 150, 180]
Ouput for 100 is: 18
Ouput for 150 is: 22
Ouput for 180 is: 24


In [8]:
import numpy as np
print('Enter No. Of Rows(ith):')
Rows = int(input())
print('Enter No. Of Columns(jth):')
Cols = int(input())
list1 = []

for i in range(1,Rows+1):
    for j in range(1,Cols+1):
        list1.append(i*j)

print('Array is:\n',np.array(list1).reshape(Rows,Cols))

Enter No. Of Rows(ith):


 3


Enter No. Of Columns(jth):


 3


Array is:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [27]:
print('Enter Comma Separated Words:')
words = input()
print('After Sorting the string is:')
words_list = words.split(',')
words_list.sort()
print(','.join(words_list))

Enter Comma Separated Words:


 Hello,Divya,Diya,Divit


After Sorting the string is:
Divit,Divya,Diya,Hello


In [25]:
print('Enter a str (whitespace seperated):')
str1 = input()
print('After Sorting the string And Removing the duplicates is:')
str_list = str1.split(' ')
set1 = set(str_list)
str_new_list = list(set1)
str_new_list.sort()
print(' '.join(str_new_list))

Enter a str (whitespace seperated):


 Heelo Diyvya Heelo


After Sorting the string And Removing the duplicates is:
Diyvya Heelo


In [39]:
s = input("Input a string")
d=l=0
for c in s:
    if c.isdigit():
        d=d+1
    elif c.isalpha():
        l=l+1
    else:
        pass
print("Letters", l)
print("Digits", d)

Input a string Divanshu 2002


Letters 8
Digits 4


In [38]:
print('Enter a String (which can contain both alphabates and numbers):')
str1 = input()
list_str = list(str1)

count_alpha = 0
count_digit = 0
str_digit = '0123456789'
list_digit = list(str_digit)

for i in range(len(list_str)):
    if list_str[i] not in list_digit:
        count_alpha += 1
        
    else:
        count_digit +=1
        

print('Total Number of characters are(Counting Space and Special Character):',count_alpha)
print('Total Number of digits are:',count_digit)

Enter a String (which can contain both alphabates and numbers):


 Divya 2002\


Total Number of characters are(Counting Space and Special Character): 7
Total Number of digits are: 4


In [40]:
Username = input('Set User Name:')
Password = input('Set Password:')

print('You successfully set your username and password!!')

print('Please Enter Your Username:')
User = input()
print('Please Enter Your Password:')
Pass = input()

if Username == User and Password == Pass:
    print('You Enter Successfully 👍!!')
else:
    print('Please try again🙄')


Set User Name: divya
Set Password: 123@


You successfully set your username and password!!
Please Enter Your Username:


 divya


Please Enter Your Password:


 123@


You Enter Successfully 👍!!
