In [1]:
import random

In [2]:
import numpy as np

In [7]:
## Write a Python Program to Add Two Matrices?

M1 = np.random.rand(10).reshape(5,2)
M2 = np.random.rand(10).reshape(5,2)

print('Addition Of Two Matrix is:')
print(M1+M2)

Addition Of Two Matrix is:
[[1.74812783 1.12874964]
 [0.43546155 1.02340161]
 [0.5114942  1.64186863]
 [1.26293033 0.44952438]
 [0.81994718 1.3567486 ]]


In [8]:
## Write a Python Program to Multiply Two Matrices?

M1 = np.linspace(4,10,10).reshape(5,2)
M2 = np.linspace(10,20,10).reshape(5,2)

print('Multiplication Of Matrix is:')
print(M1*M2)

Multiplication Of Matrix is:
[[ 40.          51.85185185]
 [ 65.18518519  80.        ]
 [ 96.2962963  114.07407407]
 [133.33333333 154.07407407]
 [176.2962963  200.        ]]


In [18]:
## Write a Python Program to Transpose a Matrix?

M1 = np.random.rand(10).reshape(2,5)
M1

print('Transpose of the Matrix is:')
M1.transpose()

Transpose of the Matrix is:


array([[0.14435865, 0.32749149],
       [0.43885121, 0.97509258],
       [0.7851096 , 0.15695044],
       [0.02029557, 0.15570502],
       [0.82168125, 0.10142392]])

In [22]:
## Write a Python Program to Sort Words in Alphabetic Order?

list1 = ['Divya','Diya','Divyanshu','Divit','Diksha','Gatik','Divyansh']
list2 = np.array(list1)
list2
np.sort(list2)

array(['Diksha', 'Divit', 'Divya', 'Divyansh', 'Divyanshu', 'Diya',
       'Gatik'], dtype='<U9')

In [26]:
## Write a Python Program to Remove Punctuation From a String?

import string

str1 = input('Enter a string :')

str1 = str1.translate(str.maketrans('', '', string.punctuation))
print(str1)

Enter a string : Hello !! My Name Is, Div yanshu


Hello  My Name Is Div yanshu


In [31]:
## Another Way
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for ele in str1:
    if ele in punc:
        str1 = str1.replace(ele, "")
print("The string after punctuation filter : " + str1)

The string after punctuation filter : Hello  My Name Is Div yanshu
